/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kalkulator;

/**
 *
 * @author Irfan Oesman Asa
 */
public class NewJFrame extends javax.swing.JFrame {
    String bil = "";
    double jumlah, bil1, bil2;
    int pilih;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Field1 = new javax.swing.JTextField();
        ButtonBackspace = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        ButtonMin = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonKali = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonTitik = new javax.swing.JButton();
        ButtonSamaDengan = new javax.swing.JButton();
        ButtonBagi = new javax.swing.JButton();
        ButtonPangkat2 = new javax.swing.JButton();
        ButtonPersen = new javax.swing.JButton();
        ButtonCLear = new javax.swing.JButton();
        ButtonMod = new javax.swing.JButton();
        ButtonPangkat3 = new javax.swing.JButton();
        ButtonAkar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        Field1.setEditable(false);
        Field1.setBackground(new java.awt.Color(42, 42, 62));
        Field1.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        Field1.setForeground(new java.awt.Color(204, 204, 204));
        Field1.setText("0");
        Field1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(85, 85, 119), 1, true));
        Field1.addActionListener(this::Field1ActionPerformed);

        ButtonBackspace.setBackground(new java.awt.Color(192, 57, 43));
        ButtonBackspace.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonBackspace.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBackspace.setText("<");
        ButtonBackspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBackspaceMouseClicked(evt);
            }
        });
        ButtonBackspace.addActionListener(this::ButtonBackspaceActionPerformed);

        ButtonPlus.setBackground(new java.awt.Color(92, 92, 255));
        ButtonPlus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPlus.setText("+");
        ButtonPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPlusMouseClicked(evt);
            }
        });
        ButtonPlus.addActionListener(this::ButtonPlusActionPerformed);

        Button9.setBackground(new java.awt.Color(45, 45, 68));
        Button9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button9.setForeground(new java.awt.Color(255, 255, 255));
        Button9.setText("9");
        Button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button9MouseClicked(evt);
            }
        });
        Button9.addActionListener(this::Button9ActionPerformed);

        Button8.setBackground(new java.awt.Color(45, 45, 68));
        Button8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button8.setForeground(new java.awt.Color(255, 255, 255));
        Button8.setText("8");
        Button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button8MouseClicked(evt);
            }
        });
        Button8.addActionListener(this::Button8ActionPerformed);

        Button7.setBackground(new java.awt.Color(45, 45, 68));
        Button7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button7.setForeground(new java.awt.Color(255, 255, 255));
        Button7.setText("7");
        Button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button7MouseClicked(evt);
            }
        });

        ButtonMin.setBackground(new java.awt.Color(92, 92, 255));
        ButtonMin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ButtonMin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMin.setText("-");
        ButtonMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMinMouseClicked(evt);
            }
        });

        Button6.setBackground(new java.awt.Color(45, 45, 68));
        Button6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button6.setForeground(new java.awt.Color(255, 255, 255));
        Button6.setText("6");
        Button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button6MouseClicked(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(45, 45, 68));
        Button5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button5.setForeground(new java.awt.Color(255, 255, 255));
        Button5.setText("5");
        Button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button5MouseClicked(evt);
            }
        });

        Button4.setBackground(new java.awt.Color(45, 45, 68));
        Button4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button4.setForeground(new java.awt.Color(255, 255, 255));
        Button4.setText("4");
        Button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button4MouseClicked(evt);
            }
        });

        Button1.setBackground(new java.awt.Color(45, 45, 68));
        Button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("1");
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(45, 45, 68));
        Button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.setText("2");
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
        });

        Button3.setBackground(new java.awt.Color(45, 45, 68));
        Button3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("3");
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
        });

        ButtonKali.setBackground(new java.awt.Color(92, 92, 255));
        ButtonKali.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ButtonKali.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKali.setText("x");
        ButtonKali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonKaliMouseClicked(evt);
            }
        });

        Button0.setBackground(new java.awt.Color(45, 45, 68));
        Button0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button0.setForeground(new java.awt.Color(255, 255, 255));
        Button0.setText("0");
        Button0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button0MouseClicked(evt);
            }
        });

        ButtonTitik.setBackground(new java.awt.Color(45, 45, 68));
        ButtonTitik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonTitik.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTitik.setText(".");
        ButtonTitik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonTitikMouseClicked(evt);
            }
        });
        ButtonTitik.addActionListener(this::ButtonTitikActionPerformed);

        ButtonSamaDengan.setBackground(new java.awt.Color(255, 107, 107));
        ButtonSamaDengan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ButtonSamaDengan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSamaDengan.setText("=");
        ButtonSamaDengan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSamaDenganMouseClicked(evt);
            }
        });

        ButtonBagi.setBackground(new java.awt.Color(92, 92, 255));
        ButtonBagi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ButtonBagi.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBagi.setText("/");

        ButtonPangkat2.setBackground(new java.awt.Color(46, 125, 107));
        ButtonPangkat2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ButtonPangkat2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPangkat2.setText("x²");
        ButtonPangkat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPangkat2MouseClicked(evt);
            }
        });

        ButtonPersen.setBackground(new java.awt.Color(123, 94, 167));
        ButtonPersen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonPersen.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPersen.setText("%");
        ButtonPersen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPersenMouseClicked(evt);
            }
        });

        ButtonCLear.setBackground(new java.awt.Color(231, 76, 60));
        ButtonCLear.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCLear.setText("C");
        ButtonCLear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCLearMouseClicked(evt);
            }
        });

        ButtonMod.setBackground(new java.awt.Color(123, 94, 167));
        ButtonMod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonMod.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMod.setText("mod");
        ButtonMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonModMouseClicked(evt);
            }
        });

        ButtonPangkat3.setBackground(new java.awt.Color(46, 125, 107));
        ButtonPangkat3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ButtonPangkat3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPangkat3.setText("x³");
        ButtonPangkat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPangkat3MouseClicked(evt);
            }
        });

        ButtonAkar.setBackground(new java.awt.Color(46, 125, 107));
        ButtonAkar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAkar.setText("√");
        ButtonAkar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAkarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonCLear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonAkar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ButtonTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonPangkat3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonPangkat2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Field1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(ButtonMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonKali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPersen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonPangkat2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonPangkat3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAkar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCLear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTitikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTitikActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button9ActionPerformed

    private void Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field1ActionPerformed
        
    }//GEN-LAST:event_Field1ActionPerformed

    private void ButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackspaceActionPerformed
    
    }//GEN-LAST:event_ButtonBackspaceActionPerformed

    private void ButtonBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackspaceMouseClicked
            String nilaiBaru;
            nilaiBaru = Field1.getText().substring(0, Field1.getText().length() - 1);
            bil = nilaiBaru;
            Field1.setText(nilaiBaru);
            if (Field1.getText().length() == 0){
                Field1.setText("0");
                bil = "";
            }
    }//GEN-LAST:event_ButtonBackspaceMouseClicked

    private void Button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button7MouseClicked
        bil += "7";
        Field1.setText(bil);
    }//GEN-LAST:event_Button7MouseClicked

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button8MouseClicked
        bil += "8";
        Field1.setText(bil);
    }//GEN-LAST:event_Button8MouseClicked

    private void Button9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button9MouseClicked
        bil += "9";
        Field1.setText(bil);
    }//GEN-LAST:event_Button9MouseClicked

    private void Button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseClicked
         bil += "4";
        Field1.setText(bil);
    }//GEN-LAST:event_Button4MouseClicked

    private void Button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button5MouseClicked
        bil += "5";
        Field1.setText(bil);
    }//GEN-LAST:event_Button5MouseClicked

    private void Button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button6MouseClicked
        bil += "6";
        Field1.setText(bil);
    }//GEN-LAST:event_Button6MouseClicked

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        bil += "1";
        Field1.setText(bil);
    }//GEN-LAST:event_Button1MouseClicked

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
        bil += "2";
        Field1.setText(bil);
    }//GEN-LAST:event_Button2MouseClicked

    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseClicked
          bil += "3";
        Field1.setText(bil);
    }//GEN-LAST:event_Button3MouseClicked

    private void Button0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button0MouseClicked
        if (!Field1.getText().equals("0")) {
        bil += "0";
        Field1.setText(bil);
        }
    }//GEN-LAST:event_Button0MouseClicked

    private void ButtonPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPlusMouseClicked
        bil1 = Double.parseDouble(Field1.getText());
        bil = "";
        pilih = 1;
    }//GEN-LAST:event_ButtonPlusMouseClicked

    private void ButtonCLearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCLearMouseClicked
        double hasil;
        bil = "";
        bil1 = 0.0;
        bil2 = 0.0;
        hasil = 0.0;
        Field1.setText("0");
    }//GEN-LAST:event_ButtonCLearMouseClicked

    private void ButtonMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinMouseClicked
        bil1 = Double.parseDouble(Field1.getText());
              Field1.setText("0");
        bil = "";
        pilih = 2;
    }//GEN-LAST:event_ButtonMinMouseClicked

    private void ButtonKaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonKaliMouseClicked
        bil1 = Double.parseDouble(Field1.getText());
        Field1.setText("0");
        bil = "";
        pilih = 3;
    }//GEN-LAST:event_ButtonKaliMouseClicked

    private void ButtonTitikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTitikMouseClicked
          if (!Field1.getText().contains(".")) {
              if (Field1.getText().equals("0")) {
                  bil += "0.";
              } else {
                  bil += ".";
                  Field1.setText(bil);
              }
        }
    }//GEN-LAST:event_ButtonTitikMouseClicked

    private void ButtonSamaDenganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSamaDenganMouseClicked
      bil2 = Double.parseDouble(Field1.getText());
      double hasil = 0;
        switch (pilih) {
            case 1:
                hasil = bil1 + bil2;
                break;
                case 2:
                hasil = bil1 - bil2;
                break;
                case 3:
                hasil = bil1 * bil2;
                break;
                case 4:
                hasil = bil1 / bil2;
                break;
                case 5:
                hasil = bil1 * (bil2 / 100);
                break;
                case 6:
                hasil = bil1 % bil2;
                 break;
            default:
                throw new AssertionError();
        }
        bil = "";
        Field1.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonSamaDenganMouseClicked

    private void ButtonPersenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPersenMouseClicked
        bil1 = Double.parseDouble(Field1.getText());
        bil = "";
        pilih = 5;
    }//GEN-LAST:event_ButtonPersenMouseClicked

    private void ButtonModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonModMouseClicked
        bil1 = Double.parseDouble(Field1.getText());
        bil = "";
        pilih = 6;
    }//GEN-LAST:event_ButtonModMouseClicked

    private void ButtonPangkat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPangkat2MouseClicked
    double nilai = Double.parseDouble(Field1.getText());
    double hasil = Math.pow(nilai, 2);
    bil = "";
    pilih = 0;
    Field1.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonPangkat2MouseClicked

    private void ButtonPangkat3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPangkat3MouseClicked
    double nilai = Double.parseDouble(Field1.getText());
    double hasil = Math.pow(nilai, 3);
    bil = "";
    pilih = 0; // reset pilihan operator!
    Field1.setText(String.valueOf(hasil));
       
    }//GEN-LAST:event_ButtonPangkat3MouseClicked

    private void ButtonAkarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAkarMouseClicked
        double nilai = Double.parseDouble(Field1.getText());
        if (nilai < 0) {
        Field1.setText("Error");
        bil = "";
        } else {
        double hasil = Math.sqrt(nilai);
        bil = "";
        Field1.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_ButtonAkarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonAkar;
    private javax.swing.JButton ButtonBackspace;
    private javax.swing.JButton ButtonBagi;
    private javax.swing.JButton ButtonCLear;
    private javax.swing.JButton ButtonKali;
    private javax.swing.JButton ButtonMin;
    private javax.swing.JButton ButtonMod;
    private javax.swing.JButton ButtonPangkat2;
    private javax.swing.JButton ButtonPangkat3;
    private javax.swing.JButton ButtonPersen;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JButton ButtonSamaDengan;
    private javax.swing.JButton ButtonTitik;
    private javax.swing.JTextField Field1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
